#ifndef VERSION_H
#define VERSION_H

#define VER_FILEVERSION 1, 0, 7, 0
#define VER_FILEVERSION_STR "1.0.7.0\0"

#define VER_PRODUCTVERSION 1, 0, 7, 0
#define VER_PRODUCTVERSION_STR "1.0.7\0"

#define VER_COMPANYNAME_STR "IAPP of BSU"
#define VER_FILEDESCRIPTION_STR "KAMEYA POWER CONTROLLER"
#define VER_INTERNALNAME_STR "KAMEYA POWER CONTROLLER"
#define VER_LEGALCOPYRIGHT_STR "2026 IAPP of BSU"
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "power_controller.exe"
#define VER_PRODUCTNAME_STR "KAMEYA POWER CONTROLLER"

#define VER_COMPANYDOMAIN_STR "http://niipfp.bsu.by"

#endif  // VERSION_H
